---
development:
  cloud_name: 'khortytsa'
  api_key: '985432737164814'
  api_secret: 'RKdAb0z1nxg26z1N0c09Rmsn2-k'
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: Rails.application.secrets.cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: Rails.application.secrets.enhance_image_tag
  static_image_support: Rails.application.secrets.static_image_support
test:
  cloud_name: Rails.application.secrets.cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: Rails.application.secrets.enhance_image_tag
  static_image_support: Rails.application.secrets.static_image_support
