---
development:
  cloud_name: Rails.application.secrets.cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: Rails.application.secrets.enhance_image_tag
  static_image_support: Rails.application.secrets.static_image_support
production:
  cloud_name: Rails.application.secrets.cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: Rails.application.secrets.enhance_image_tag
  static_image_support: Rails.application.secrets.static_image_support
test:
  cloud_name: Rails.application.secrets.cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: Rails.application.secrets.enhance_image_tag
  static_image_support: Rails.application.secrets.static_image_support
